[package]
name = "KiThe"
version = "0.1.1"
edition = "2021"
author = "Gleb Zasllavsky"
license = "MIT"
keywords = [ "thermodynamics", "chemistry", "CFD", "chemical_kinetics"]
description = "A collection of structures and functions useful for chemical kinetics, chemical thermodynamics, combustion, heat and mass transfer, shock tubes and so on and so far. Work in progress. Advices and contributions will be appreciated"
repository = "https://github.com/Gleb-Zaslavsky/KiThe"
[dependencies]
regex = "1.10.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"



