pub mod bsplines;
pub mod exp_engine_api;
pub mod exp_kinetics_column_manipulation;
pub mod exp_kinetics_smooth_filter;
pub mod experiment_series_main;
pub mod experiment_series_main_test;
mod filters_smoothing_test;
pub mod ndarray_statistics;
pub mod one_experiment_dataset;
pub mod one_experiment_dataset_test;
pub mod savgol;
pub mod savgol2;
pub mod splines;
pub mod testing_mod;
